version: '3'
services:

  db:
    image: mariadb:11.0.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: "/usr/src/app"
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app